name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, add a minimal code sample to reproduce the issue
      render: python

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of shap-enhanced are you running?
      options:
        - 0.0.1a3 (Latest)
        - 0.0.1a2
        - 0.0.1a1
        - Other (please specify in additional context)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
      value: |
        - OS: [e.g. Ubuntu 20.04, Windows 11, macOS 12]
        - Python version: [e.g. 3.10.5]
        - PyTorch version: [e.g. 1.12.0]
        - CUDA version (if applicable): [e.g. 11.7]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here (screenshots, logs, etc.)